# Generated by Django 5.2.5 on 2025-08-20 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servidores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Descanso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FERIAS', 'Férias'), ('LICENCA', 'Licença'), ('FOLGA_COMP', 'Folga compensatória'), ('AFASTAMENTO', 'Afastamento'), ('ATESTADO', 'Atestado')], max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descansos_criados', to=settings.AUTH_USER_MODEL)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descansos', to='servidores.servidor')),
            ],
            options={
                'ordering': ['-data_inicio', '-id'],
                'indexes': [models.Index(fields=['servidor', 'data_inicio'], name='descanso_de_servido_85a914_idx'), models.Index(fields=['servidor', 'data_fim'], name='descanso_de_servido_0f31fe_idx')],
            },
        ),
    ]
