# Generated by Django 5.2.5 on 2026-03-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("descanso", "0003_feriado_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="descanso",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("RECESSO", "Recesso"),
                    ("FERIAS", "Férias"),
                    ("LICENCA", "Licença"),
                    ("DIARIAS", "Diárias"),
                    ("FOLGA_COMP", "Folga compensatória"),
                    ("FOLGA_ELEITORAL", "Folga eleitoral"),
                    ("AFASTAMENTO", "Afastamento"),
                    ("ATESTADO", "Atestado"),
                ],
                max_length=20,
            ),
        ),
    ]
