# Generated by Django 5.2.5 on 2026-03-09 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_no_options'),
        ('metas', '0005_sync_meta_titles_with_atividade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacaoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_programacao', models.DateField()),
                ('programacao_id', models.PositiveIntegerField(blank=True, null=True)),
                ('item_id', models.PositiveIntegerField(blank=True, null=True)),
                ('evento', models.CharField(choices=[('atividade_criada', 'Atividade criada'), ('atividade_removida', 'Atividade removida'), ('meta_alterada', 'Meta alterada'), ('observacao_alterada', 'Observacao alterada'), ('servidor_adicionado', 'Servidor adicionado'), ('servidor_removido', 'Servidor removido'), ('veiculo_alterado', 'Veiculo alterado'), ('status_alterado', 'Status alterado'), ('programacao_excluida', 'Programacao excluida')], max_length=40)),
                ('origem', models.CharField(blank=True, default='', max_length=30)),
                ('titulo_item', models.CharField(blank=True, default='', max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('status_antes', models.CharField(blank=True, default='', max_length=40)),
                ('status_depois', models.CharField(blank=True, default='', max_length=40)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('snapshot_antes', models.JSONField(blank=True, default=dict)),
                ('snapshot_depois', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('meta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_programacao', to='metas.meta')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_programacao', to='core.no')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_programacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historico da programacao',
                'verbose_name_plural': 'Historicos da programacao',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['unidade', 'data_programacao'], name='relatorios__unidade_e1acb5_idx'), models.Index(fields=['item_id', 'criado_em'], name='relatorios__item_id_c03a7b_idx'), models.Index(fields=['evento', 'criado_em'], name='relatorios__evento_b558a7_idx')],
            },
        ),
    ]
