# Generated by Django 5.2.5 on 2025-08-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='no',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
