# Generated by Django 5.2.5 on 2025-08-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ativado',
            field=models.BooleanField(default=False, help_text='Se o usuário já concluiu o primeiro acesso'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='senha_provisoria',
            field=models.CharField(blank=True, help_text='Token de ativação para primeiro acesso', max_length=100, null=True),
        ),
    ]
