# Generated by Django 5.2.5 on 2025-08-15 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_ativado_userprofile_senha_provisoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_read', models.BooleanField(default=True)),
                ('can_write', models.BooleanField(default=False)),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('LOCAL', 'Local'), ('RESTRICTED', 'Restricted')], default='RESTRICTED', max_length=20)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='core.userprofile')),
            ],
        ),
    ]
