# Generated by Django 5.2.5 on 2025-08-15 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_policy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='no',
            options={'permissions': [('assumir_unidade', 'Pode assumir unidades')]},
        ),
    ]
