# Generated by Django 5.2.5 on 2025-10-30 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True, default='')),
                ('concluida', models.BooleanField(default=False)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'programar_atividades_programacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, default='')),
                ('concluido', models.BooleanField(default=False)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'programar_atividades_programacaoitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramacaoItemServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'programar_atividades_programacaoitemservidor',
                'managed': False,
            },
        ),
    ]
