# Generated by Django 5.2.5 on 2025-09-03 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_no_options'),
        ('metas', '0002_alter_meta_atividade_alter_meta_options_and_more'),
        ('servidores', '0001_initial'),
        ('veiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('concluida', models.BooleanField(default=False)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('concluida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programacoes_concluidas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programacoes', to='core.no')),
            ],
            options={
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True)),
                ('concluido', models.BooleanField(default=False)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_programados_concluidos', to=settings.AUTH_USER_MODEL)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_programados', to='metas.meta')),
                ('programacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='programar_atividades.programacao')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='veiculos.veiculo')),
            ],
            options={
                'ordering': ['programacao_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacaoItemServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servidores', to='programar_atividades.programacaoitem')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servidores.servidor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='programacao',
            constraint=models.UniqueConstraint(fields=('unidade', 'data'), name='uniq_programacao_unidade_data'),
        ),
        migrations.AddIndex(
            model_name='programacaoitemservidor',
            index=models.Index(fields=['item'], name='programar_a_item_id_224fab_idx'),
        ),
        migrations.AddConstraint(
            model_name='programacaoitemservidor',
            constraint=models.UniqueConstraint(fields=('item', 'servidor'), name='uniq_item_servidor'),
        ),
    ]
