# Generated by Django 5.2.5 on 2025-08-19 23:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0006_alter_no_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('quantidade_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('quantidade_restante', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('escopo', models.CharField(choices=[('UNIDADE', 'Unidade'), ('SERVIDOR', 'Servidor'), ('VEICULO', 'Veículo'), ('GERAL', 'Geral (da unidade para baixo)')], default='UNIDADE', max_length=15)),
                ('propagar_descendentes', models.BooleanField(default=False)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades_criadas', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('unidade_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades_origem', to='core.no')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AtribuicaoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_atribuida', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('quantidade_concluida', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('origem_propagacao', models.BooleanField(default=False)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='atividades.atividade')),
                ('atribuido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('unidade_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes_recebidas', to='core.no')),
            ],
            options={
                'ordering': ['-criado_em'],
                'unique_together': {('atividade', 'unidade_destino')},
            },
        ),
    ]
