# Generated by Django 5.2.5 on 2025-08-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={'ordering': ['titulo']},
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='escopo',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='propagar_descendentes',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='quantidade_restante',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='quantidade_total',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='target_content_type',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='target_object_id',
        ),
        migrations.AddField(
            model_name='atividade',
            name='area',
            field=models.CharField(choices=[('ANIMAL', 'Animal'), ('VEGETAL', 'Vegetal'), ('APOIO', 'Apoio'), ('OUTROS', 'Outros')], default='OUTROS', max_length=10),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='titulo',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='AtribuicaoAtividade',
        ),
    ]
