# Generated by Django 5.2.5 on 2025-08-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_alter_atividade_options_remove_atividade_data_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='area',
            field=models.CharField(choices=[('ANIMAL', 'Animal'), ('VEGETAL', 'Vegetal'), ('ANIMAL_VEGETAL', 'Animal e Vegetal'), ('APOIO', 'Apoio'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20),
        ),
    ]
