# Generated by ChatGPT on 2025-10-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atividades", "0003_alter_atividade_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atividade",
            name="titulo",
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name="atividade",
            constraint=models.UniqueConstraint(
                fields=("titulo", "unidade_origem"), name="atividade_unique_titulo_unidade"
            ),
        ),
    ]
