# Generated by Django 5.2.5 on 2025-08-11 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPolitica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('permissoes', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
            options={
                'ordering': ['nome'],
                'permissions': [('manage_policies', 'Pode gerenciar perfis e políticas')],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='Ativo', max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhas', to='organizacao.unidade')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcance', models.CharField(choices=[('self', 'Apenas esta unidade'), ('subtree', 'Esta unidade e descendentes')], default='self', max_length=16)),
                ('perfil_politica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organizacao.perfilpolitica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacao.unidade')),
            ],
            options={
                'ordering': ['usuario__username', 'unidade__nome'],
                'unique_together': {('usuario', 'unidade', 'perfil_politica', 'alcance')},
            },
        ),
    ]
