# Generated by Django 5.2.5 on 2025-08-20 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servidores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantão',
                'verbose_name_plural': 'Plantoes',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='SemanaPlantao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('info', models.CharField(blank=True, max_length=200)),
                ('plantao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanas', to='plantao.plantao')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidores.servidor')),
            ],
            options={
                'verbose_name': 'SemanaPlantao',
                'verbose_name_plural': 'Semanas de Plantão',
                'ordering': ['dia'],
            },
        ),
    ]
