# Generated by Django 5.2.5 on 2025-08-21 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantao', '0001_initial'),
        ('servidores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantao',
            name='nome',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('ordem', models.IntegerField(default=0)),
                ('plantao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanas', to='plantao.plantao')),
            ],
            options={
                'verbose_name': 'Semana de Plantão',
                'verbose_name_plural': 'Semanas de Plantão',
                'ordering': ['ordem', 'inicio'],
            },
        ),
        migrations.CreateModel(
            name='SemanaServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=0)),
                ('telefone_snapshot', models.CharField(blank=True, max_length=60)),
                ('info', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='plantao.semana')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidores.servidor')),
            ],
            options={
                'verbose_name': 'Servidor na Semana',
                'verbose_name_plural': 'Servidores nas Semanas',
                'ordering': ['semana__ordem', 'ordem'],
            },
        ),
        migrations.DeleteModel(
            name='SemanaPlantao',
        ),
    ]
