# Generated by Django 5.2.5 on 2025-08-22 19:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_no_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('quantidade_alvo', models.PositiveIntegerField(default=0)),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('encerrada', models.BooleanField(default=False)),
                ('atividade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metas', to='metas.atividade')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas_criadas_por', to=settings.AUTH_USER_MODEL)),
                ('unidade_criadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas_criadas', to='core.no')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MetaAlocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_alocada', models.PositiveIntegerField()),
                ('atribuida_em', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('atribuida_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atribuicoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='metas.meta')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redistribuicoes', to='metas.metaalocacao')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas_recebidas', to='core.no')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressoMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('quantidade', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('alocacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso', to='metas.metaalocacao')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progresso_registrado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='meta',
            index=models.Index(fields=['data_limite'], name='metas_meta_data_li_a17e88_idx'),
        ),
        migrations.AddIndex(
            model_name='meta',
            index=models.Index(fields=['unidade_criadora'], name='metas_meta_unidade_e40516_idx'),
        ),
        migrations.AddIndex(
            model_name='metaalocacao',
            index=models.Index(fields=['meta', 'unidade'], name='metas_metaa_meta_id_c5d021_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metaalocacao',
            unique_together={('meta', 'unidade', 'parent')},
        ),
        migrations.AddIndex(
            model_name='progressometa',
            index=models.Index(fields=['data'], name='metas_progr_data_870ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='progressometa',
            index=models.Index(fields=['alocacao'], name='metas_progr_alocaca_2f75f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='progressometa',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='progresso_quantidade_gt_0'),
        ),
    ]
