# Generated by Django 5.2.5 on 2025-08-25 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_alter_atividade_area'),
        ('metas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='atividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metas', to='atividades.atividade'),
        ),
        migrations.AlterModelOptions(
            name='meta',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Meta', 'verbose_name_plural': 'Metas'},
        ),
        migrations.AlterModelOptions(
            name='metaalocacao',
            options={'verbose_name': 'Alocação de Meta', 'verbose_name_plural': 'Alocações de Metas'},
        ),
        migrations.AlterModelOptions(
            name='progressometa',
            options={'ordering': ['-data', '-criado_em'], 'verbose_name': 'Progresso de Meta', 'verbose_name_plural': 'Progresso de Metas'},
        ),
        migrations.DeleteModel(
            name='Atividade',
        ),
    ]
