# Generated by Django 5.2.5 on 2026-04-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0005_sync_meta_titles_with_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='modo_alocacao',
            field=models.CharField(choices=[('auto', 'Automatica'), ('manual', 'Manual')], default='manual', max_length=16),
        ),
    ]
